# Generated by Django 3.0.8 on 2020-09-17 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Number', models.IntegerField()),
                ('Name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Number', models.IntegerField(null='true')),
                ('Name', models.CharField(max_length=20, null='true')),
                ('Description', models.CharField(max_length=200, null='true')),
                ('Duration', models.IntegerField(null='true')),
                ('Risks', models.CharField(max_length=200, null='true')),
                ('Attention', models.CharField(max_length=200, null='true')),
                ('OtherOption', models.BooleanField(null='true')),
                ('PreparatoryStage', models.BooleanField(null='true')),
                ('Experiment', models.ForeignKey(null='true', on_delete=django.db.models.deletion.CASCADE, to='home.Experiment')),
            ],
        ),
        migrations.CreateModel(
            name='SubStage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Number', models.IntegerField(null='true')),
                ('Criterion', models.CharField(max_length=200, null='true')),
                ('Name', models.CharField(max_length=200, null='true')),
                ('Risks', models.CharField(max_length=200, null='true')),
                ('Condition', models.CharField(max_length=200, null='true')),
                ('Attention', models.CharField(max_length=200, null='true')),
                ('Duration', models.IntegerField(null='true')),
                ('Picture', models.BooleanField(null='true')),
                ('Runtime', models.IntegerField(null='true')),
                ('OtherOption', models.BooleanField(null='true')),
                ('Main', models.ForeignKey(null='true', on_delete=django.db.models.deletion.CASCADE, to='home.Stage')),
                ('Parent', models.ForeignKey(null='true', on_delete=django.db.models.deletion.CASCADE, to='home.SubStage')),
            ],
        ),
        migrations.CreateModel(
            name='Reagents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Stage')),
            ],
        ),
        migrations.CreateModel(
            name='ProtectiveEquipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Stage')),
            ],
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ParameterName', models.CharField(max_length=30)),
                ('From', models.IntegerField(null='true')),
                ('To', models.IntegerField(null='true')),
                ('Unit', models.CharField(max_length=30, null='true')),
                ('ExactValue', models.IntegerField(null='true')),
                ('Equipment', models.CharField(max_length=302, null='true')),
                ('MainStage', models.ForeignKey(null='true', on_delete=django.db.models.deletion.CASCADE, to='home.Stage')),
                ('SubStage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.SubStage')),
            ],
        ),
        migrations.CreateModel(
            name='Paragraph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('PreparatoryStage', models.IntegerField(null='true')),
                ('PreparatoryStageName', models.CharField(max_length=302, null='true')),
                ('Stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Stage')),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Stage')),
            ],
        ),
        migrations.CreateModel(
            name='Doc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Stage')),
            ],
        ),
        migrations.CreateModel(
            name='Dishes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Stage')),
            ],
        ),
        migrations.CreateModel(
            name='CalcParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ParameterName', models.CharField(max_length=30)),
                ('Unit', models.CharField(max_length=30, null='true')),
                ('VarName', models.CharField(max_length=30, null='true')),
                ('MainStage', models.ForeignKey(null='true', on_delete=django.db.models.deletion.CASCADE, to='home.Stage')),
                ('SubStage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.SubStage')),
            ],
        ),
    ]
