# Generated by Django 3.0.8 on 2020-09-17 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExeExperiment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Laboratorian', models.IntegerField()),
                ('Number', models.IntegerField()),
                ('Name', models.CharField(max_length=20)),
                ('Experiments', models.ForeignKey(null='true', on_delete=django.db.models.deletion.DO_NOTHING, to='home.Experiment')),
            ],
        ),
        migrations.CreateModel(
            name='ExeStage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50, null='true')),
                ('Number', models.IntegerField(null='true')),
                ('Check', models.BooleanField(null='true')),
                ('PreparatoryStage', models.BooleanField(null='true')),
                ('ExeExperiment', models.ForeignKey(null='true', on_delete=django.db.models.deletion.CASCADE, to='lab.ExeExperiment')),
                ('Stage', models.ForeignKey(null='true', on_delete=django.db.models.deletion.DO_NOTHING, to='home.Stage')),
            ],
        ),
        migrations.CreateModel(
            name='Samples',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Laboratorian', models.IntegerField()),
                ('Check', models.BooleanField(null='true')),
                ('Customer', models.CharField(max_length=100, null='true')),
                ('CustomerCode', models.CharField(max_length=100, null='true')),
                ('Deposit', models.CharField(max_length=100, null='true')),
                ('WellNumber', models.CharField(max_length=100, null='true')),
                ('SelectionDate', models.DateField(max_length=100, null='true')),
                ('ActNumber', models.CharField(max_length=100, null='true')),
                ('LabName', models.CharField(max_length=100, null='true')),
                ('LabSurname', models.CharField(max_length=100, null='true')),
                ('LabPatronymic', models.CharField(max_length=100, null='true')),
                ('LabCode', models.CharField(max_length=50, null='true')),
                ('ReceiptDate', models.CharField(max_length=100, null='true')),
                ('Comment', models.CharField(max_length=1000, null='true')),
            ],
        ),
        migrations.CreateModel(
            name='ExeSubStage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Number', models.IntegerField(null='true')),
                ('Criterion', models.CharField(max_length=200, null='true')),
                ('Name', models.CharField(max_length=200, null='true')),
                ('Risks', models.CharField(max_length=200, null='true')),
                ('Condition', models.CharField(max_length=200, null='true')),
                ('Attention', models.CharField(max_length=200, null='true')),
                ('Duration', models.IntegerField(null='true')),
                ('Picture', models.BooleanField(null='true')),
                ('UrlPicture', models.CharField(max_length=200, null='true')),
                ('OtherOption', models.BooleanField(null='true')),
                ('Check', models.BooleanField(null='true')),
                ('ExeStage', models.ForeignKey(null='true', on_delete=django.db.models.deletion.CASCADE, to='lab.ExeStage')),
                ('Parent', models.ForeignKey(null='true', on_delete=django.db.models.deletion.CASCADE, to='lab.ExeSubStage')),
            ],
        ),
        migrations.CreateModel(
            name='ExeReagents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Check', models.BooleanField(null='true')),
                ('Name', models.CharField(max_length=50)),
                ('ExeStage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.ExeStage')),
            ],
        ),
        migrations.CreateModel(
            name='ExeProtectiveEquipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Check', models.BooleanField(null='true')),
                ('Name', models.CharField(max_length=50)),
                ('ExeStage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.ExeStage')),
            ],
        ),
        migrations.CreateModel(
            name='ExeParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ParameterName', models.CharField(max_length=30)),
                ('From', models.IntegerField(null='true')),
                ('To', models.IntegerField(null='true')),
                ('ExactValue', models.IntegerField(null='true')),
                ('Value', models.IntegerField(null='true')),
                ('Unit', models.CharField(max_length=30, null='true')),
                ('Equipment', models.CharField(max_length=302, null='true')),
                ('ExeMainStage', models.ForeignKey(null='true', on_delete=django.db.models.deletion.CASCADE, to='lab.ExeStage')),
                ('ExeSubStage', models.ForeignKey(null='true', on_delete=django.db.models.deletion.CASCADE, to='lab.ExeSubStage')),
            ],
        ),
        migrations.CreateModel(
            name='ExeParagraph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('ExePreparatoryStage', models.IntegerField(null='true')),
                ('ExePreparatoryStageName', models.CharField(max_length=302, null='true')),
                ('ExeStage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.ExeStage')),
            ],
        ),
        migrations.AddField(
            model_name='exeexperiment',
            name='Samples',
            field=models.ForeignKey(null='true', on_delete=django.db.models.deletion.DO_NOTHING, to='lab.Samples'),
        ),
        migrations.CreateModel(
            name='ExeEquipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Check', models.BooleanField(null='true')),
                ('Name', models.CharField(max_length=50)),
                ('ExeStage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.ExeStage')),
            ],
        ),
        migrations.CreateModel(
            name='ExeDoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Check', models.BooleanField(null='true')),
                ('Name', models.CharField(max_length=50)),
                ('ExeStage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.ExeStage')),
            ],
        ),
        migrations.CreateModel(
            name='ExeDishes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Check', models.BooleanField(null='true')),
                ('Name', models.CharField(max_length=50)),
                ('ExeStage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.ExeStage')),
            ],
        ),
        migrations.CreateModel(
            name='ExeCalcParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ParameterName', models.CharField(max_length=30)),
                ('Unit', models.CharField(max_length=30, null='true')),
                ('VarName', models.CharField(max_length=30, null='true')),
                ('ExeMainStage', models.ForeignKey(null='true', on_delete=django.db.models.deletion.CASCADE, to='lab.ExeStage')),
                ('ExeSubStage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.ExeSubStage')),
            ],
        ),
    ]
