# Generated by Django 3.0.8 on 2020-09-24 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='C:\\Users\\kosac\\PycharmProjects\\Checklist\\media')),
            ],
        ),
        migrations.RemoveField(
            model_name='exesubstage',
            name='UrlPicture',
        ),
    ]
